 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/political_parties", type: :request do
  # PoliticalParty. As you add validations to PoliticalParty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PoliticalParty.create! valid_attributes
      get political_parties_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      political_party = PoliticalParty.create! valid_attributes
      get political_party_url(political_party)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_political_party_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      political_party = PoliticalParty.create! valid_attributes
      get edit_political_party_url(political_party)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PoliticalParty" do
        expect {
          post political_parties_url, params: { political_party: valid_attributes }
        }.to change(PoliticalParty, :count).by(1)
      end

      it "redirects to the created political_party" do
        post political_parties_url, params: { political_party: valid_attributes }
        expect(response).to redirect_to(political_party_url(PoliticalParty.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PoliticalParty" do
        expect {
          post political_parties_url, params: { political_party: invalid_attributes }
        }.to change(PoliticalParty, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post political_parties_url, params: { political_party: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested political_party" do
        political_party = PoliticalParty.create! valid_attributes
        patch political_party_url(political_party), params: { political_party: new_attributes }
        political_party.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the political_party" do
        political_party = PoliticalParty.create! valid_attributes
        patch political_party_url(political_party), params: { political_party: new_attributes }
        political_party.reload
        expect(response).to redirect_to(political_party_url(political_party))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        political_party = PoliticalParty.create! valid_attributes
        patch political_party_url(political_party), params: { political_party: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested political_party" do
      political_party = PoliticalParty.create! valid_attributes
      expect {
        delete political_party_url(political_party)
      }.to change(PoliticalParty, :count).by(-1)
    end

    it "redirects to the political_parties list" do
      political_party = PoliticalParty.create! valid_attributes
      delete political_party_url(political_party)
      expect(response).to redirect_to(political_parties_url)
    end
  end
end
